# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_procedimiento', models.CharField(max_length=60)),
                ('SMLV', models.FloatField()),
                ('precio', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.Paciente')),
            ],
        ),
    ]
