# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaFarmaceutica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_forma_farmaceutica', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_historial', models.DateTimeField(auto_now_add=True)),
                ('descripcion_historia', models.TextField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_presentacion_unidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_procedimiento', models.CharField(max_length=60)),
                ('SMLV', models.FloatField()),
                ('precio', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_comercial', models.CharField(max_length=60)),
                ('nombre_comercial', models.CharField(max_length=60)),
                ('nombre_generico', models.CharField(max_length=60)),
                ('concentracion', models.CharField(max_length=60)),
                ('presentacion_cantidad', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('indicaciones', models.TextField(max_length=200)),
                ('principal_indicacion', models.CharField(max_length=60)),
                ('lote', models.CharField(max_length=60)),
                ('invima', models.CharField(max_length=60)),
                ('fecha_de_vencimiento', models.DateTimeField(auto_now=True)),
                ('cantidad_existentes', models.IntegerField()),
                ('forma_farmaceutica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.FormaFarmaceutica')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Laboratorio')),
                ('presentacion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PresentacionUnidad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_producto', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.TipoProducto'),
        ),
        migrations.AddField(
            model_name='historial',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Paciente'),
        ),
        migrations.AddField(
            model_name='historial',
            name='producto',
            field=models.ManyToManyField(to='inventario.Producto'),
        ),
    ]
