# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionCantidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_presentacion_cantidad', models.CharField(max_length=10)),
                ('descripcion_presentacion_cantidad', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Presentanci\xf3n de cantidades',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion_cantidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PresentacionCantidad'),
        ),
    ]
