# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20180514_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
