# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20180514_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimiento',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Procedimiento',
        ),
    ]
