# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20180514_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentacionunidad',
            options={'verbose_name_plural': 'Presentanci\xf3n de unidades'},
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(auto_now=True),
        ),
    ]
