# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_auto_20180514_1334'),
        ('Paciente', '0002_auto_20180514_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_historial', models.DateTimeField(auto_now_add=True)),
                ('descripcion_historia', models.TextField(blank=True, max_length=800, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.Paciente')),
                ('producto', models.ManyToManyField(to='inventario.Producto')),
            ],
        ),
    ]
