# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=75, verbose_name='Nombre del paciente')),
                ('especie', models.CharField(max_length=75, null=True)),
                ('raza', models.CharField(max_length=75, null=True)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('motivo_consulta', models.TextField(null=True, verbose_name='Motivo de la consulta')),
                ('medica_tratante', models.CharField(max_length=75, null=True, verbose_name='Medico tratante')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.IntegerField(verbose_name='N\xfamero de contacto')),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='fk_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.Propietario', verbose_name='Propietario'),
        ),
    ]
