# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especie', models.CharField(max_length=60)),
                ('descripcion_especie', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.IntegerField(verbose_name='N\xfamero de contacto')),
                ('profesion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_raza', models.CharField(max_length=60)),
                ('descripcion_raza', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medica_tratante',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.Especie', verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.Raza', verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico_tratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.Medico', verbose_name='Medico tratante'),
        ),
    ]
