# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=40)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.IntegerField(verbose_name='N\xfamero de contacto')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='especie',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='medica_tratante',
            field=models.CharField(max_length=75, null=True, verbose_name='Medico tratante'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_consulta',
            field=models.TextField(null=True, verbose_name='Motivo de la consulta'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='raza',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_paciente',
            field=models.CharField(max_length=75, verbose_name='Nombre del paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fk_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.Propietario', verbose_name='Propietario'),
        ),
    ]
